"""create store operating hours

Revision ID: 077498dfaa91
Revises: 2eb2bce458d5
Create Date: 2026-07-31 09:03:59.937934+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "077498dfaa91"
down_revision: str | Sequence[str] | None = "2eb2bce458d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_operating_hours",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default="Asia/Kolkata",
            nullable=False,
        ),
        sa.Column("opening_time", sa.Time(), nullable=True),
        sa.Column("closing_time", sa.Time(), nullable=True),
        sa.Column(
            "is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_24_hours", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "priority", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(effective_from IS NULL AND effective_until IS NULL) OR "
            "(effective_from IS NOT NULL AND effective_until IS NOT NULL "
            "AND effective_from < effective_until)",
            name=op.f("ck_store_operating_hours_effective_period_valid"),
        ),
        sa.CheckConstraint(
            "(is_closed AND NOT is_24_hours AND opening_time IS NULL "
            "AND closing_time IS NULL) OR "
            "(is_24_hours AND NOT is_closed AND opening_time IS NULL "
            "AND closing_time IS NULL) OR "
            "(NOT is_closed AND NOT is_24_hours AND opening_time IS NOT NULL "
            "AND closing_time IS NOT NULL AND opening_time < closing_time)",
            name=op.f("ck_store_operating_hours_hours_mode_valid"),
        ),
        sa.CheckConstraint(
            "char_length(timezone) BETWEEN 1 AND 64",
            name=op.f("ck_store_operating_hours_timezone_length"),
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN 0 AND 6",
            name=op.f("ck_store_operating_hours_day_of_week_valid"),
        ),
        sa.CheckConstraint(
            "notes IS NULL OR char_length(notes) <= 500",
            name=op.f("ck_store_operating_hours_notes_length"),
        ),
        sa.CheckConstraint(
            "priority >= 0", name=op.f("ck_store_operating_hours_priority_nonnegative")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_store_operating_hours_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_operating_hours_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_operating_hours")),
    )
    op.create_index(
        "ix_store_hours_active_store",
        "store_operating_hours",
        ["store_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_store_hours_effective_range",
        "store_operating_hours",
        ["store_id", "effective_from", "effective_until"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_store_hours_resolution",
        "store_operating_hours",
        ["store_id", "day_of_week", "priority"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_store_hours_resolution",
        table_name="store_operating_hours",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_store_hours_effective_range",
        table_name="store_operating_hours",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_store_hours_active_store",
        table_name="store_operating_hours",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("store_operating_hours")
    # ### end Alembic commands ###
