"""create store analytics foundation

Revision ID: 0f01b7088f73
Revises: 077498dfaa91
Create Date: 2026-07-31 09:39:58.614424+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0f01b7088f73"
down_revision: str | Sequence[str] | None = "077498dfaa91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_daily_metrics",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column(
            "profile_views", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "gallery_views", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "media_uploads", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "staff_invitations",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "staff_acceptances",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "verification_submissions",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "verification_approvals",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "verification_rejections",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "storage_bytes",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "active_members", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "profile_views >= 0 AND gallery_views >= 0 AND media_uploads >= 0 "
            "AND staff_invitations >= 0 AND staff_acceptances >= 0 "
            "AND verification_submissions >= 0 "
            "AND verification_approvals >= 0 "
            "AND verification_rejections >= 0 AND active_members >= 0",
            name=op.f("ck_store_daily_metrics_counters_nonnegative"),
        ),
        sa.CheckConstraint(
            "storage_bytes >= 0",
            name=op.f("ck_store_daily_metrics_storage_bytes_nonnegative"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_store_daily_metrics_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_daily_metrics_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_daily_metrics")),
        sa.UniqueConstraint("store_id", "metric_date", name="store_metric_date_unique"),
    )
    op.create_index(
        "ix_store_daily_metrics_metric_date",
        "store_daily_metrics",
        ["metric_date"],
        unique=False,
    )
    op.create_index(
        "ix_store_daily_metrics_store_date",
        "store_daily_metrics",
        ["store_id", "metric_date"],
        unique=False,
    )
    op.create_index(
        "ix_store_daily_metrics_store_id",
        "store_daily_metrics",
        ["store_id"],
        unique=False,
    )
    op.create_table(
        "store_metric_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "profile_view",
                "gallery_view",
                "media_upload",
                "media_deleted",
                "staff_invitation",
                "staff_acceptance",
                "verification_submission",
                "verification_approval",
                "verification_rejection",
                name="store_metric_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_metric_events_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_metric_events")),
    )
    op.create_index(
        "ix_store_metric_events_event_type",
        "store_metric_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_store_metric_events_occurred_at",
        "store_metric_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_store_metric_events_store_id",
        "store_metric_events",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        "ix_store_metric_events_store_occurred",
        "store_metric_events",
        ["store_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_store_metric_events_store_occurred", table_name="store_metric_events"
    )
    op.drop_index("ix_store_metric_events_store_id", table_name="store_metric_events")
    op.drop_index(
        "ix_store_metric_events_occurred_at", table_name="store_metric_events"
    )
    op.drop_index("ix_store_metric_events_event_type", table_name="store_metric_events")
    op.drop_table("store_metric_events")
    op.drop_index("ix_store_daily_metrics_store_id", table_name="store_daily_metrics")
    op.drop_index("ix_store_daily_metrics_store_date", table_name="store_daily_metrics")
    op.drop_index(
        "ix_store_daily_metrics_metric_date", table_name="store_daily_metrics"
    )
    op.drop_table("store_daily_metrics")
    # ### end Alembic commands ###
