"""create store verification workflow

Revision ID: 0f7538229016
Revises: d48004d70e46
Create Date: 2026-07-31 06:58:29.476380+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0f7538229016"
down_revision: str | Sequence[str] | None = "d48004d70e46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_verifications",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by_id", sa.Uuid(), nullable=False),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "in_review",
                "approved",
                "rejected",
                name="store_verification_workflow_status",
                native_enum=False,
            ),
            server_default="submitted",
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("business_license", sa.String(length=200), nullable=True),
        sa.Column("tax_registration", sa.String(length=200), nullable=True),
        sa.Column("owner_identity", sa.String(length=300), nullable=True),
        sa.Column("address_proof", sa.String(length=300), nullable=True),
        sa.Column("additional_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'submitted' AND reviewed_by_id IS NULL "
            "AND review_started_at IS NULL AND reviewed_at IS NULL "
            "AND rejection_reason IS NULL) OR "
            "(status = 'in_review' AND reviewed_by_id IS NOT NULL "
            "AND review_started_at IS NOT NULL AND reviewed_at IS NULL "
            "AND rejection_reason IS NULL) OR "
            "(status = 'approved' AND reviewed_by_id IS NOT NULL "
            "AND review_started_at IS NOT NULL AND reviewed_at IS NOT NULL "
            "AND rejection_reason IS NULL) OR "
            "(status = 'rejected' AND reviewed_by_id IS NOT NULL "
            "AND review_started_at IS NOT NULL AND reviewed_at IS NOT NULL "
            "AND rejection_reason IS NOT NULL)",
            name=op.f("ck_store_verifications_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "char_length(additional_notes) <= 2000",
            name=op.f("ck_store_verifications_additional_notes_length"),
        ),
        sa.CheckConstraint(
            "char_length(address_proof) <= 300",
            name=op.f("ck_store_verifications_address_proof_length"),
        ),
        sa.CheckConstraint(
            "char_length(business_license) <= 200",
            name=op.f("ck_store_verifications_business_license_length"),
        ),
        sa.CheckConstraint(
            "char_length(owner_identity) <= 300",
            name=op.f("ck_store_verifications_owner_identity_length"),
        ),
        sa.CheckConstraint(
            "char_length(review_notes) <= 4000",
            name=op.f("ck_store_verifications_review_notes_length"),
        ),
        sa.CheckConstraint(
            "char_length(tax_registration) <= 200",
            name=op.f("ck_store_verifications_tax_registration_length"),
        ),
        sa.CheckConstraint(
            "rejection_reason IS NULL OR "
            "char_length(btrim(rejection_reason)) BETWEEN 1 AND 1000",
            name=op.f("ck_store_verifications_rejection_reason_length"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_store_verifications_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["identity_users.id"],
            name=op.f("fk_store_verifications_reviewed_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_verifications_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["identity_users.id"],
            name=op.f("fk_store_verifications_submitted_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_verifications")),
        sa.UniqueConstraint("store_id", name="store_verifications_store_unique"),
    )
    op.create_index(
        "ix_store_verifications_pending",
        "store_verifications",
        ["submitted_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('submitted', 'in_review')"),
    )
    op.create_index(
        "ix_store_verifications_reviewed_by_status",
        "store_verifications",
        ["reviewed_by_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_store_verifications_status_submitted_at",
        "store_verifications",
        ["status", "submitted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_store_verifications_status_submitted_at", table_name="store_verifications"
    )
    op.drop_index(
        "ix_store_verifications_reviewed_by_status", table_name="store_verifications"
    )
    op.drop_index(
        "ix_store_verifications_pending",
        table_name="store_verifications",
        postgresql_where=sa.text("status IN ('submitted', 'in_review')"),
    )
    op.drop_table("store_verifications")
    # ### end Alembic commands ###
