"""create store media platform

Revision ID: 2eb2bce458d5
Revises: 47f0ff7d40b8
Create Date: 2026-07-31 08:24:13.119832+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2eb2bce458d5"
down_revision: str | Sequence[str] | None = "47f0ff7d40b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_media",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "logo", "banner", "gallery", name="store_media_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                "deleted",
                name="store_media_status",
                native_enum=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("extension", sa.String(length=10), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("orientation", sa.Integer(), nullable=False),
        sa.Column("aspect_ratio", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=False),
        sa.Column(
            "display_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'deleted' AND deleted_at IS NOT NULL) OR "
            "(status <> 'deleted' AND deleted_at IS NULL)",
            name=op.f("ck_store_media_soft_delete_consistent"),
        ),
        sa.CheckConstraint(
            "checksum_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_store_media_checksum_sha256_valid"),
        ),
        sa.CheckConstraint(
            "aspect_ratio > 0", name=op.f("ck_store_media_aspect_ratio_positive")
        ),
        sa.CheckConstraint(
            "display_order >= 0", name=op.f("ck_store_media_display_order_nonnegative")
        ),
        sa.CheckConstraint(
            "file_size > 0", name=op.f("ck_store_media_file_size_positive")
        ),
        sa.CheckConstraint(
            "orientation BETWEEN 1 AND 8", name=op.f("ck_store_media_orientation_valid")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_store_media_version_positive")
        ),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_store_media_dimensions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_media_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["identity_users.id"],
            name=op.f("fk_store_media_uploaded_by_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_media")),
        sa.UniqueConstraint("object_key", name="object_key_unique"),
    )
    op.create_index(
        "ix_store_media_active_store_type_order",
        "store_media",
        ["store_id", "media_type", "display_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_store_media_display_order", "store_media", ["display_order"], unique=False
    )
    op.create_index(
        "ix_store_media_media_type", "store_media", ["media_type"], unique=False
    )
    op.create_index(
        "ix_store_media_not_deleted",
        "store_media",
        ["store_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_store_media_status", "store_media", ["status"], unique=False)
    op.create_index(
        "ix_store_media_store_id", "store_media", ["store_id"], unique=False
    )
    op.create_index(
        "ix_store_media_uploaded_by", "store_media", ["uploaded_by"], unique=False
    )
    op.create_index(
        "uq_store_media_active_banner",
        "store_media",
        ["store_id"],
        unique=True,
        postgresql_where=sa.text(
            "media_type = 'banner' AND status = 'active' AND deleted_at IS NULL"
        ),
    )
    op.create_index(
        "uq_store_media_active_logo",
        "store_media",
        ["store_id"],
        unique=True,
        postgresql_where=sa.text(
            "media_type = 'logo' AND status = 'active' AND deleted_at IS NULL"
        ),
    )
    op.create_index(
        "uq_store_media_checksum",
        "store_media",
        ["store_id", "checksum_sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_store_media_checksum",
        table_name="store_media",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_store_media_active_logo",
        table_name="store_media",
        postgresql_where=sa.text(
            "media_type = 'logo' AND status = 'active' AND deleted_at IS NULL"
        ),
    )
    op.drop_index(
        "uq_store_media_active_banner",
        table_name="store_media",
        postgresql_where=sa.text(
            "media_type = 'banner' AND status = 'active' AND deleted_at IS NULL"
        ),
    )
    op.drop_index("ix_store_media_uploaded_by", table_name="store_media")
    op.drop_index("ix_store_media_store_id", table_name="store_media")
    op.drop_index("ix_store_media_status", table_name="store_media")
    op.drop_index(
        "ix_store_media_not_deleted",
        table_name="store_media",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_store_media_media_type", table_name="store_media")
    op.drop_index("ix_store_media_display_order", table_name="store_media")
    op.drop_index(
        "ix_store_media_active_store_type_order",
        table_name="store_media",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("store_media")
    # ### end Alembic commands ###
