"""create store membership management

Revision ID: 47f0ff7d40b8
Revises: 0f7538229016
Create Date: 2026-07-31 07:34:54.888132+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "47f0ff7d40b8"
down_revision: str | Sequence[str] | None = "0f7538229016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_memberships",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "manager",
                "staff",
                name="store_membership_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "declined",
                "suspended",
                "removed",
                "expired",
                name="store_membership_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("invited_by_id", sa.Uuid(), nullable=False),
        sa.Column("invitation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(role = 'owner' AND status = 'active' AND accepted_at IS NOT NULL AND "
            "invitation_expires_at IS NULL) OR role <> 'owner'",
            name=op.f("ck_store_memberships_owner_active"),
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND accepted_at IS NULL AND removed_at IS NULL AND "
            "invitation_expires_at IS NOT NULL) OR (status IN ('active', 'suspended') "
            "AND accepted_at IS NOT NULL AND removed_at IS NULL) OR (status IN "
            "('declined', 'removed', 'expired') AND removed_at IS NOT NULL)",
            name=op.f("ck_store_memberships_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_store_memberships_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["identity_users.id"],
            name=op.f("fk_store_memberships_invited_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_memberships_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_store_memberships_user_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_memberships")),
    )
    op.create_index(
        "ix_store_memberships_pending_expiry",
        "store_memberships",
        ["invitation_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_store_memberships_store_status_created",
        "store_memberships",
        ["store_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_store_memberships_user_status",
        "store_memberships",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_store_memberships_active_owner",
        "store_memberships",
        ["store_id"],
        unique=True,
        postgresql_where=sa.text("role = 'owner' AND status = 'active'"),
    )
    op.create_index(
        "uq_store_memberships_live_user",
        "store_memberships",
        ["store_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('active', 'suspended')"),
    )
    op.create_index(
        "uq_store_memberships_pending_user",
        "store_memberships",
        ["store_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_store_memberships_pending_user",
        table_name="store_memberships",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "uq_store_memberships_live_user",
        table_name="store_memberships",
        postgresql_where=sa.text("status IN ('active', 'suspended')"),
    )
    op.drop_index(
        "uq_store_memberships_active_owner",
        table_name="store_memberships",
        postgresql_where=sa.text("role = 'owner' AND status = 'active'"),
    )
    op.drop_index("ix_store_memberships_user_status", table_name="store_memberships")
    op.drop_index(
        "ix_store_memberships_store_status_created", table_name="store_memberships"
    )
    op.drop_index(
        "ix_store_memberships_pending_expiry",
        table_name="store_memberships",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("store_memberships")
    # ### end Alembic commands ###
