"""create identity persistence

Revision ID: b6d38dd509e1
Revises:
Create Date: 2026-07-30 08:12:49.519441+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6d38dd509e1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_login_attempts",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "email = lower(btrim(email)) AND length(email) BETWEEN 3 AND 320",
            name=op.f("ck_identity_login_attempts_email_normalized"),
        ),
        sa.CheckConstraint(
            "success OR (reason IS NOT NULL AND "
            "length(btrim(reason)) BETWEEN 1 AND 100)",
            name=op.f("ck_identity_login_attempts_failed_reason_present"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_login_attempts")),
    )
    op.create_index(
        "ix_identity_login_attempts_email_occurred",
        "identity_login_attempts",
        ["email", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_identity_login_attempts_ip_occurred",
        "identity_login_attempts",
        ["ip_address", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_identity_login_attempts_occurred_at",
        "identity_login_attempts",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "identity_permissions",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("resource", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "description IS NULL OR length(description) <= 500",
            name=op.f("ck_identity_permissions_description_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(action)) BETWEEN 1 AND 100",
            name=op.f("ck_identity_permissions_action_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(name)) BETWEEN 1 AND 150",
            name=op.f("ck_identity_permissions_name_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(resource)) BETWEEN 1 AND 100",
            name=op.f("ck_identity_permissions_resource_length"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_identity_permissions_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_permissions")),
        sa.UniqueConstraint("name", name="uq_identity_permissions_name"),
        sa.UniqueConstraint(
            "resource", "action", name="uq_identity_permissions_resource_action"
        ),
    )
    op.create_table(
        "identity_roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_immutable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "NOT is_immutable OR is_system",
            name=op.f("ck_identity_roles_immutable_role_is_system"),
        ),
        sa.CheckConstraint(
            "description IS NULL OR length(description) <= 500",
            name=op.f("ck_identity_roles_description_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(name)) BETWEEN 1 AND 100",
            name=op.f("ck_identity_roles_name_length"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_identity_roles_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_roles")),
        sa.UniqueConstraint("name", name="uq_identity_roles_name"),
    )
    op.create_table(
        "identity_users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_locked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "password_hash LIKE '$argon2id$%'",
            name=op.f("ck_identity_users_password_hash_argon2id"),
        ),
        sa.CheckConstraint(
            "(is_email_verified AND email_verified_at IS NOT NULL) OR "
            "(NOT is_email_verified AND email_verified_at IS NULL)",
            name=op.f("ck_identity_users_email_verification_consistent"),
        ),
        sa.CheckConstraint(
            "deleted_at IS NULL OR NOT is_active",
            name=op.f("ck_identity_users_deleted_user_inactive"),
        ),
        sa.CheckConstraint(
            "email = btrim(email) AND length(email) BETWEEN 3 AND 320",
            name=op.f("ck_identity_users_email_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) BETWEEN 1 AND 120",
            name=op.f("ck_identity_users_display_name_length"),
        ),
        sa.CheckConstraint(
            "normalized_email = lower(btrim(email))",
            name=op.f("ck_identity_users_normalized_email_matches_email"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_identity_users_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_users_created_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_users_updated_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_users")),
    )
    op.create_index(
        "ix_identity_users_created_by_id",
        "identity_users",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_identity_users_normalized_email",
        "identity_users",
        ["normalized_email"],
        unique=True,
    )
    op.create_index(
        "ix_identity_users_updated_by_id",
        "identity_users",
        ["updated_by_id"],
        unique=False,
    )
    op.create_table(
        "identity_email_verification_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_identity_email_verification_tokens_token_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_email_verification_tokens_user_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_identity_email_verification_tokens")
        ),
    )
    op.create_index(
        "ix_identity_email_verification_tokens_token_hash",
        "identity_email_verification_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_identity_email_verification_tokens_user_expiry",
        "identity_email_verification_tokens",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "identity_password_history",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "password_hash LIKE '$argon2id$%'",
            name=op.f("ck_identity_password_history_password_hash_argon2id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_password_history_user_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_password_history")),
        sa.UniqueConstraint(
            "user_id", "password_hash", name="uq_identity_password_history_user_hash"
        ),
    )
    op.create_index(
        "ix_identity_password_history_user_created",
        "identity_password_history",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "identity_password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_identity_password_reset_tokens_token_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_password_reset_tokens_user_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_password_reset_tokens")),
    )
    op.create_index(
        "ix_identity_password_reset_tokens_token_hash",
        "identity_password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_identity_password_reset_tokens_user_expiry",
        "identity_password_reset_tokens",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "identity_refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=120), nullable=False),
        sa.Column("browser", sa.String(length=120), nullable=True),
        sa.Column("operating_system", sa.String(length=120), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("user_agent", sa.String(length=1024), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "refresh_token_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_identity_refresh_sessions_refresh_token_hash_sha256"),
        ),
        sa.CheckConstraint(
            "expires_at > last_activity_at",
            name=op.f("ck_identity_refresh_sessions_expiry_after_activity"),
        ),
        sa.CheckConstraint(
            "length(btrim(device_name)) BETWEEN 1 AND 120",
            name=op.f("ck_identity_refresh_sessions_device_name_length"),
        ),
        sa.CheckConstraint(
            "length(user_agent) BETWEEN 1 AND 1024",
            name=op.f("ck_identity_refresh_sessions_user_agent_length"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_identity_refresh_sessions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_refresh_sessions_user_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_refresh_sessions")),
    )
    op.create_index(
        "ix_identity_refresh_sessions_refresh_token_hash",
        "identity_refresh_sessions",
        ["refresh_token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_identity_refresh_sessions_user_active",
        "identity_refresh_sessions",
        ["user_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("NOT is_revoked"),
    )
    op.create_index(
        "ix_identity_refresh_sessions_user_id",
        "identity_refresh_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "identity_role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_role_permissions_assigned_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["identity_permissions.id"],
            name=op.f(
                "fk_identity_role_permissions_permission_id_identity_permissions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["identity_roles.id"],
            name=op.f("fk_identity_role_permissions_role_id_identity_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_id", name=op.f("pk_identity_role_permissions")
        ),
    )
    op.create_index(
        "ix_identity_role_permissions_assigned_by_id",
        "identity_role_permissions",
        ["assigned_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_identity_role_permissions_permission_id",
        "identity_role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_table(
        "identity_user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_user_roles_assigned_by_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["identity_roles.id"],
            name=op.f("fk_identity_user_roles_role_id_identity_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_user_roles_user_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "role_id", name=op.f("pk_identity_user_roles")
        ),
    )
    op.create_index(
        "ix_identity_user_roles_assigned_by_id",
        "identity_user_roles",
        ["assigned_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_identity_user_roles_role_id",
        "identity_user_roles",
        ["role_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_identity_user_roles_role_id", table_name="identity_user_roles")
    op.drop_index(
        "ix_identity_user_roles_assigned_by_id", table_name="identity_user_roles"
    )
    op.drop_table("identity_user_roles")
    op.drop_index(
        "ix_identity_role_permissions_permission_id",
        table_name="identity_role_permissions",
    )
    op.drop_index(
        "ix_identity_role_permissions_assigned_by_id",
        table_name="identity_role_permissions",
    )
    op.drop_table("identity_role_permissions")
    op.drop_index(
        "ix_identity_refresh_sessions_user_id", table_name="identity_refresh_sessions"
    )
    op.drop_index(
        "ix_identity_refresh_sessions_user_active",
        table_name="identity_refresh_sessions",
        postgresql_where=sa.text("NOT is_revoked"),
    )
    op.drop_index(
        "ix_identity_refresh_sessions_refresh_token_hash",
        table_name="identity_refresh_sessions",
    )
    op.drop_table("identity_refresh_sessions")
    op.drop_index(
        "ix_identity_password_reset_tokens_user_expiry",
        table_name="identity_password_reset_tokens",
    )
    op.drop_index(
        "ix_identity_password_reset_tokens_token_hash",
        table_name="identity_password_reset_tokens",
    )
    op.drop_table("identity_password_reset_tokens")
    op.drop_index(
        "ix_identity_password_history_user_created",
        table_name="identity_password_history",
    )
    op.drop_table("identity_password_history")
    op.drop_index(
        "ix_identity_email_verification_tokens_user_expiry",
        table_name="identity_email_verification_tokens",
    )
    op.drop_index(
        "ix_identity_email_verification_tokens_token_hash",
        table_name="identity_email_verification_tokens",
    )
    op.drop_table("identity_email_verification_tokens")
    op.drop_index("ix_identity_users_updated_by_id", table_name="identity_users")
    op.drop_index("ix_identity_users_normalized_email", table_name="identity_users")
    op.drop_index("ix_identity_users_created_by_id", table_name="identity_users")
    op.drop_table("identity_users")
    op.drop_table("identity_roles")
    op.drop_table("identity_permissions")
    op.drop_index(
        "ix_identity_login_attempts_occurred_at", table_name="identity_login_attempts"
    )
    op.drop_index(
        "ix_identity_login_attempts_ip_occurred", table_name="identity_login_attempts"
    )
    op.drop_index(
        "ix_identity_login_attempts_email_occurred",
        table_name="identity_login_attempts",
    )
    op.drop_table("identity_login_attempts")
    # ### end Alembic commands ###
