"""create store domain

Revision ID: d48004d70e46
Revises: c3d91e7a4b62
Create Date: 2026-07-31 06:07:22.242310+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d48004d70e46"
down_revision: str | Sequence[str] | None = "c3d91e7a4b62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("website", sa.String(length=2048), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("logo_url", sa.String(length=2048), nullable=True),
        sa.Column("banner_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_review",
                "active",
                "suspended",
                "closed",
                name="store_status",
                native_enum=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "unverified",
                "pending",
                "verified",
                "rejected",
                name="store_verification_status",
                native_enum=False,
            ),
            server_default="unverified",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'", name=op.f("ck_stores_slug_canonical")
        ),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)",
            name=op.f("ck_stores_coordinates_complete"),
        ),
        sa.CheckConstraint(
            "char_length(email) BETWEEN 3 AND 320", name=op.f("ck_stores_email_length")
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 2 AND 150", name=op.f("ck_stores_name_length")
        ),
        sa.CheckConstraint(
            "char_length(phone) BETWEEN 7 AND 32", name=op.f("ck_stores_phone_length")
        ),
        sa.CheckConstraint(
            "description IS NULL OR char_length(description) <= 2000",
            name=op.f("ck_stores_description_length"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name=op.f("ck_stores_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_stores_longitude_range"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_stores_version_positive")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity_users.id"],
            name=op.f("fk_stores_owner_id_identity_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("slug", name="slug_unique"),
    )
    op.create_index(
        "ix_stores_active_public",
        "stores",
        ["verification_status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'active'"),
    )
    op.create_index(
        "ix_stores_owner_id_status", "stores", ["owner_id", "status"], unique=False
    )
    op.create_index(
        "ix_stores_status_verification",
        "stores",
        ["status", "verification_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is proven safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stores_status_verification", table_name="stores")
    op.drop_index("ix_stores_owner_id_status", table_name="stores")
    op.drop_index(
        "ix_stores_active_public",
        table_name="stores",
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'active'"),
    )
    op.drop_table("stores")
    # ### end Alembic commands ###
